### ISSUE TITLE
Docker inside docker

### ISSUE THREAD

**Issue by asad-awadia** [marghidanu/werk#23]
hello @marghidanu 

Great project! This is very useful and well made

I wanted to know if i am running werk inside a container can i still use docker executor?

**Comment by marghidanu** [comment]
Hello, and thank you very much!

By default, the Docker executor tries to connect to the Docker daemon using a Unix socket on this path: `/var/run/docker.sock`; you could mount this path inside your Docker container, and maybe this could work. 

You can find more information on the Docker client used here: https://github.com/marghidanu/docr/blob/master/src/docr.cr

**Comment by asad-awadia** [comment]
Thanks! will try that out
